# Site settings
title: CodeScouts.de
email: florian@codescouts.de
baseurl: "/"
url: "https://codescouts.de"
domain: codescouts.de
#url: "http://localhost:4000"

# Build settings
markdown: kramdown
permalink: pretty
